### ISSUE TITLE
How to sync 2 sliders?

### ISSUE THREAD

**Issue by teddytei** [loomchild/webflow-alpinejs#2]
Hi, @loomchild ! This is just awesome! You just introduced a completely new framework to the low-code community. So thank you for making it available for webflowers! I used it to create a slider with a button navigation and it perfectly just like in your components. 

Now I'm building a website where I need to sync 2 sliders. Arrow clicks, active slide indexes should be in sync. I tried to follow the alpine attributes you provided in your components but had no luck. So if you could create smth similar in your components it would help tremendously! And I'm sure there are lots of ppl want to create smth similar to mine.

Here very similar example to what I want to achieve:
https://jsfiddle.net/glebkema/b6c2ayeg/

**Comment by loomchild** [comment]
Hi Teddy,

Thank you for your question. The problem of inter-component communication is interesting in general, I think I will publish an article about this soon.

To solve your issue, you can use custom event dispatching, more specifically [window/global events](http://alpinejs.dev/magics/dispatch#dispatching-to-components).

However, coming from Vue.js/Vuex world, my preferred solution would involve a new feature in Alpine.js 3, a [store magic](http://alpinejs.dev/magics/store). 

First you need to do is to set up a shared currentSlide variable, by putting this code at the bottom of the page in an HTML Embed:
```
<script>
document.addEventListener('alpine:init', () => {
  Alpine.store('currentSlide', 0)
})
</script>
```

Then create two slider components, both with the following `x-init` directive, together with `x-data="slider"` directive:
```
$watch('$store.currentSlide', value => slide = value); $watch('slide', value => $store.currentSlide = value)
```

Now, changing one slider will change the other, and vice-versa.

Also note that I didn't bother to check if value has changed before modifying it to avoid infinite recursion (something like `value => { if (slide !== value) slide = value }`, since Alpine.js seems to be doing it automatically.

Here's the link to complete solution:
https://preview.webflow.com/preview/alpinejs?utm_medium=preview_link&utm_source=designer&utm_content=alpinejs&preview=fa7b8979fc6916cfc44f3d7313816007&pageId=60e1abe9efdd5086935cc976&workflow=preview

And you can see it in action here:
https://alpinejs.webflow.io/multi-component

**Comment by teddytei** [comment]
I can't thank you enough @loomchild! It's working perfectly! 

I decided to implement your solution in the next phase. Due to the tight launch schedule, I chose to go with your first slider component with `.slider-links` underneath. 

However, now in our case, every `.slider-link` needs to have a different color when has .active class. If I could add a color custom attribute to every slider-link upon render through Alpine, I can target the elements with custom attributes through CSS. But I have no clue how to add custom attributes to template elements. I'm not sure if it's the right way, but if you have another solution to assign different active state colors to every link, our project will be 100% done.

![Component screenshot](https://user-images.githubusercontent.com/63253252/124871497-b06fd500-dff6-11eb-8186-ae4212cbc67f.png)

**Comment by loomchild** [comment]
Sorry, I don't understand the problem. You can add a custom v-bind:class attribute (https://alpinejs.dev/directives/bind#binding-classes) to a div wrapped inside a template. I don't think it's related to Webflow, it should be the same as in standard Alpine.js.

Unfortunately I don't currently have time to suggest a specific solution at the moment.
