### ISSUE TITLE
Decouple AlpineJS from the lib code

### ISSUE THREAD

**Issue by parasshah195** [loomchild/webflow-alpinejs#9]
I'd prefer using just the connector extension and embed AlpineJS by myself to use a different version than the one locked into in this library.

Can you please de-couple AlpineJS lib import from this connector functionality?

**Comment by loomchild** [comment]
Hi.

Thanks for your suggestion.

For now, I prefer to keep it bundled, so webflow-alpinejs is a wrapper. It makes it simpler to use, and I can rely on specific Alpine version features when implementing components.

If you want to use a different Alpine.js version, then I suggest forking this project. Please also note that I don't actively develop it, since I'm personally not using Webflow anymore.
